name: build mobile
on: [push]

jobs:
  build-ios:
    runs-on: macos-latest
    strategy:
      matrix:
      arch: [x86_64, armv7, arm64]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      
      - name: Setting up mac os
        run: |
          chmod +x ./.github/setup_macos.sh
          ./.github/setup_macos.sh

      - name: Build lib ${{ matrix.arch }}
        run: |
          chmod +x ./.github/build_lib.sh
          ./.github/build_lib.sh ${{ matrix.arch }}

      - name: upload ios ${{ matrix.arch }} Artefact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.arch }}
          path: ../lib-ledger-core-artifacts/ios/${{ matrix.arch }}

  build-ios-universal:
    runs-on: macos-latest
    needs: build-ios
    steps:
      - name: Download armv7
        uses: actions/download-artifact@v1
        with:
          name: armv7

      - name: Download arm64
        uses: actions/download-artifact@v1
        with:
          name: armv64

      - name: Print the final result
        shell: bash
        run: |
          lipo -create armv7/ledger-core.framework/ledger-core arm64/ledger-core.framework/ledger-core -o ledger-core
          mkdir -p universal/ledger-core.framework
          mv ledger-core universal/ledger-core.framework/
          cp armv7/ledger-core.framework/Info.plist universal/ledger-core.framework/
          install_name_tool -add_rpath "@executable_path/Frameworks/universal" universal/ledger-core.framework/ledger-core
	  lipo -info universal/ledger-core.framework/ledger-core

      - name: upload ios universal Artifact
        uses: actions/upload-artifact@v1
        with:
          name: universal
          path: ../lib-ledger-core-artifacts/universal

