name: build mobile
on: [push]

jobs:
  nightly-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      
      - uses: sinoru/actions-setup-xcode@v1.1
        with:
          xcode-version: '10.0' # Exact version of a Xcode version to use
          apple-id: 'henri.ly-ext@ledger.fr' # Apple ID to download from Apple Developer when Xcode not available in local
          apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}

      - name: Setting up mac os
        run: |
          chmod +x ./.github/setup_macos.sh
          ./.github/setup_macos.sh

      - name: Build lib armv7
        run: |
          chmod +x ./.github/build_lib.sh
          ./.github/build_lib.sh armv7

      - name: upload ios armv7 Artefact
        uses: actions/upload-artifact@v1
        with:
          name: armv7
          path: ../lib-ledger-core-artifacts/armv7
 
